### ISSUE TITLE
WithLabel fails to retrieve items when a label value is not set

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/kubernetes-fluent-client#15]
`WithLabel(key: string, value?: string)` only works if `value` is set.

> Filter the query by the given label. If no value is specified, the label simply must exist.

Evidence:

```js
  const pkgSecrets = await K8s(kind.Secret)
  .InNamespace("zarf")
  .WithLabel("app.kubernetes.io/managed-by", "zarf")
  .Get();

  console.log(pkgSecrets.items.map(s => s.metadata?.labels))
  ```
  
  will yield (truncated):
  
  ```js
  [
  {
    'app.kubernetes.io/managed-by': 'zarf',
    'package-deploy-info': 'init'
  },
  {
    'app.kubernetes.io/managed-by': 'zarf',
    'package-deploy-info': 'dos-games'
  },
  ]
  ```
  
  but adding `.WithLabel("package-deploy-info")` will result in `[]`

**Comment by jeff-mccoy** [comment]
ah I yeah I think that's a mismatch from how [Pepr](https://pepr.dev/) was processing labels in javascript vs actual label selectors, should just be a simple update to make the value required in TS.
