### ISSUE TITLE
`npx kubernetes-fluent-client@v3.0.2 crd` command outputs .ts files that must be edited before use

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/kubernetes-fluent-client#374]
### Environment

Device and OS: Ubuntu 24.04
App version: v3.0.2
Kubernetes distro being used: n/a

### Definition of Done
- [ ] e2e test (in Kubernetes Fluent Client)
- [ ] No manual intervention 

**Potential look at the e2e test around PolicyReports**

### Steps to reproduce

1. Run this command:
    ```
    npx kubernetes-fluent-client@v3.0.2 crd https://github.com/kubernetes-sigs/wg-policy-prototypes/raw/master /policy-report/crd/v1alpha2/wgpolicyk8s.io_clusterpolicyreports.yaml $(pwd)
    ```
1. Open the generated files with a TS-aware IDE.

### Expected result
An error-free .ts file should be generated.

### Actual Result
The requested .ts file is generated but it has TS errors.

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/user-attachments/assets/14785152-ddf4-4766-9988-852be3a54ad1)

### Severity/Priority
Annoying

### Additional Context
Problem can be worked around by manually editing the generated files, but... that's annoying to have to do.

**Comment by mjnagel** [comment]
In my case I'm also seeing some weirdness around `spec` for my generated CRD. Typically we resolve this by deleting the `apiVersion`, `kind`, `metadata`, and changing `spec` to `spec?`.

![Screenshot 2024-09-06 at 10 36 36 AM](https://github.com/user-attachments/assets/6d908d2f-e9e5-4640-8248-8dba6aadc272)

Example to reproduce:
```console
npx kubernetes-fluent-client crd https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.76.1/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml <some file path to put CRD type>
```

**Comment by btlghrants** [comment]
Found a link to the "fix" I was using during Dash Days PolicyReport excellent example.  

https://github.com/defenseunicorns/pepr-excellent-examples/blob/ade93b0142086dce50eae6df180618b8d9f9261e/_helpers/dev/cli.mts#L164

This was built into the dev CLI (as a hack) but could probably be used as a starting point for polishing / moving into Pepr.
